### ISSUE TITLE
Re-evaluate MacOS support...?

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#1038]
https://www.youtube.com/watch?v=Yt3DbfIVXDQ

Dawid (not a typo) makes some great points in this video about the current state of gaming on the Mac. It's atrocious; and, quote: "I don't want Apple anywhere near the game industry."

**Comment by ldicker83** [comment]
I mean, sure? But really the ultimate point here is that mac gaming is where it is because developers don't bother porting their software properly.

Granted it can be a real hassle to put together an App Bundle for mac without knowing what you're doing. I've been banging my head on a desk for awhile to get an OutpostHD mac bundle ready for distribution and it's been a headache and a half.

The same could be said for Visual Studio though it's not quite as rough.

**Comment by DanRStevens** [comment]
Yeah, this isn't something I can take seriously. We're not going to strip Mac support just because someone doesn't like Mac.

Besides, Mac builds are done with the `makefile`, largely the same as Linux. There isn't really that much difference in the actual build between Linux and Mac. Mostly it's just a slightly different environment in terms of dependency install, and a different version of Clang.

I don't know much about Mac bundling. That's something we've never supported.

**Comment by ldicker83** [comment]
The builds for mac are basically the same, but distribution is a little less simple for developers. There are two possible ways to do it -- I can either develop and xcode project that builds a Swift based app that then calls an embedded C++ CLI tool... or I can write a package installer app which will install the needed dependencies and binaries where they need to go and set up an Alias for the application either in the Applications folder or on the Desktop (not sure what's best practices for macOS yet).

I'm finding it really difficult to figure out the xcode bundling so I'm considering just using an installer script that handles it for us though it's not really the 'mac way' of doing things... but eh, whatever, this isn't a commercial product :D

**Comment by DanRStevens** [comment]
Could just leave it to Mac people to figure out for now. I mean, the code compiles on a Mac, so they're not totally unsupported. As it stands now, we don't really have any expertise in bundling software for Mac, and we maybe need to be careful what we spend limited time and energy on.

I'm sure we'll get there eventually, but if we're busy with other stuff meanwhile, and someone more knowledgeable happens to come along and do Mac bundling for us, then hey, that would be nice. I certainly wouldn't object to such help.

**Comment by ldicker83** [comment]
It compiles without change on an Intel based mac. M1/M2 mac's have different settings for Homebrew which was annoying to figure out -- basically we'll need to add a "Building from source on macOS" and have an addendum for Apple silicon.

Homebrew basically builds to /opt/Homebrew/include and /opt/Homebrew/lib instead of wherever it goes on Intel macs. Not sure why the change but for me the easiest solution was to add these to the correct $PATH environment variables. Can add this as an aside to a "Building on Mac" document.

Separate issue from this but thought I'd mention it since it took a bit to figure out for me.
