### ISSUE TITLE
test project does not compile in VS2017 or VS2019

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#186]
The platform toolset for the test project is vs142 explicitly instead of %(DefaultPlatformToolset) at some point so VS2017 no longer compiles.

Language is also not set so C++17 features (such as string_view) do not compile (found this when trying to compile with VS2019, which has the platform toolset set to v142.)

Attempted to change the PlatformToolset to $(DefaultPlatformToolset) and the project thinks this value is v100 which is VS2010 and really not installed on anyone's machine.

Explicitly setting it to v142 causes VS2017 to not compile and setting it to v141 will hinder VS2019.

**Comment by DanRStevens** [comment]
I was speaking with Leeor a few days ago, and we were thinking of removing the VS2017 project file. Less to maintain with just the VS2019 project file.

Might make sense to standardize on the VS2019 project file, and whatever toolset that supports.

**Comment by cugone** [comment]
In that case, I totally agree.

**Comment by cugone** [comment]
It may be a vcpkg issue on my end but `gtest.lib` can't be found for the test project. Is there a project setting or additional library that isn't being referenced or vcpkg command I missed other than `install gtest:x86/x64-windows`?

**Comment by DanRStevens** [comment]
The `gtest.lib` and `gtest_main.lib` should be referenced by `AdditionalDependencies` under the LInker settings. The referenced libraries should be found by `vcpkg` now after the update (rather than NuGet).

I'm not sure what happened on your system. It seems to work on AppVeyor. Hopefully the above can help you debug. Maybe you have a conflicting local vcpkg setup. Or maybe not all project configurations were updated.
