### ISSUE TITLE
Mark Filesystem class as deprecated

### ISSUE THREAD

**Issue by ldicker83** [lairworks/nas2d-core#209]
Future versions of NAS2D will drop the `Filesystem` class entirely. See #118 and #179.

When NAS2D was first born (circa 2008/2009), the C++ standard library had no built in way to properly deal with the native filesystem. C++17's `std::filesystem` effectively solves this issue (minus Apple continuing to not provide an actual implementation).

Anyway, because of this, the `NAS2D::Filesystem` object has basically become obsolete. Users of NAS2D should be encouraged to use the C++17 std::filesystem implementation and move away from `Filesystem`.

**Comment by cugone** [comment]
@ldicker83 
@DanRStevens 

Well poop. I thought this was going to be as simple as marking the class `[[deprecated("reason")]]` but Microsoft's "Enable SDL checks" option goes against standard and emits an error instead of a warning when "use of a function marked deprecated" or "use of a function marked pragma deprecated" is detected. So far the only "fixes" to the issue are to disable the SDL checks option via changing the property page `C++ > General > SDL checks > No (/sdl-)`, in which the warning and message appear or "disable specific warnings" via `C++ > Advanced > Disable Specific Warnings > 4996`. in which the warning and message to NOT appear.

See: https://docs.microsoft.com/en-us/cpp/build/reference/sdl-enable-additional-security-checks?view=vs-2019 for everything the SDL checks protect against.

and MS's response to the many people complaining about [[deprecated]] being an error:
https://developercommunity.visualstudio.com/content/problem/164550/c4996-shown-as-error-by-default.html

Any thoughts on how to proceed?

**Comment by DanRStevens** [comment]
Interesting, though I can see how deprecated methods may have been deprecated for security reasons, so I can understand why Security Development Lifecycle checks would consider such warnings as errors.

Maybe just the one check can be reset to a warning rather than an error:

> C4996 | /we4996 | Use of a function marked as deprecated.

However....

----

I don't think we're quite ready to deprecate this. Downstream projects still rely on `Filesystem`, and some aspects of what `Filesystem` provided have no alternative. Namely, platform specific write folders. Until we provide an alternate solution, I think we should hold off on deprecating `Filesystem`.

Issue #179 is about clarifying which aspects of `Filesystem` are currently being used, and what we want from the design of that component. The C++ standard library can replace much of what `Filesystem` was handling, but not all of it. In particular, we used PhysFS to handle platform specific write folders, which has no replacement, and which is still quite important. We also make use of the virtual filesystem capabilities, but only in a minor way, and this can be reasonably dropped.

I think we need a new issue to provided needed replacement functionality, which this issue will depend upon.

**Comment by cugone** [comment]
Did some further reading, the setting can be overridden by specifying the warning level warning:

`C/C++ > Command Line > Add "/w44996" to text box`

This works and the error is reverted to a warning.

@DanRStevens  "Deprecated" doesn't mean "remove right now", so we can at least deprecate it now to warn users that it "will be removed in the future" and fix the issues you have with it, making sure to port over the changes to the `std::filesystem` version before fully removing it.

**Comment by DanRStevens** [comment]
I still disagree about doing the deprecation right now. I strongly believe things should not be deprecated until a workaround is provided. In particular, the deprecation should include a message that at least hints at how to update the code, such as naming an alternate method or feature that can be used.

Additionally, deprecation warnings are very troublesome for developers who have enabled warnings as errors. This is commonly done on CI builds, as only errors will cause the CI build to fail, and thus alert developers about a problem. Normally warnings would result in a passed build so they are easily missed. If however a deprecation warning is issues, and warnings are promoted to errors, and there is no workaround available yet, there is no way to fix the build.

Warnings as errors can also be used locally to speed up the development cycle when debugging something that is badly broken. I have used it a few times in the past.

----

I would consider Issue #212 (at minimum) as currently blocking this Issue. We may want to give some consideration as to other potential concerns that would hamper a transition though.

**Comment by cugone** [comment]
Apple now has support for `<filesystem>` header. CircleCI supports the required targets as well.

See https://github.com/lairworks/nas2d-core/issues/179#issuecomment-566124388

**Comment by DanRStevens** [comment]
Good news.

----

As per my comment in #179, I think we actually need to retain the `Filesystem` class. The implementation of `Filesystem` can change though, so it relies on `<filesystem>` rather than PhysFS.
