### ISSUE TITLE
Consider removing customizations to TinyXML and just use TinyXML2

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#239]
After reading #14, it's unclear what the rationale for the custom modifications on top of TinyXML is and why they were needed.

Now-a-days, up-to-date TinyXML2 performs better than the older, obsolete, TinyXML and its interface is not hard to understand. Writing a very thin wrapper (i.e. typedefs and a single namespace containing free functions) around TinyXML2 to implement desired functionality is trivial (most importantly, iteration of elements/attributes and tree validation.) and achieves the same goals to hide the C-like interface of TinyXML2 while allowing projects to still use the full functionality of the whole library if they want to.

**Comment by DanRStevens** [comment]
I would be interested in having an upgraded TinyXML. Particularly if it can be accessed through a package manager such as `vcpkg` or `nuget`.

I noticed some of the code warnings come from the TinyXML code, so having an updated version managed by an external package manager would likely clear out some of those warnings.

**Comment by ldicker83** [comment]
I removed all functions that weren't needed and renamed some objects and namespaces to offer a cleaner interface.

But, I'm planning on removing TinyXML as a dependency -- XML services are out of the scope of what NAS2D is intended to be.

**Comment by DanRStevens** [comment]
I did a bit of poking around with TinyXML2. The API is mostly very similar. I think it would be possible to upgrade. However, due to the widespread use of XML code, there would be substantial breaking changes. That is particularly true of downstream projects, such as OPHD. It might be wise to try and minimize some of those changes before attempting an upgrade.

----

I noticed 3 main types of changes:
- A few minor structural changes, such as returning `const` references
- More substantial changes (iteration changes, factory functions for new node elements)
- TinyXML2 uses UpperCamelCase names, rather than lowerCamelCase

The first category should be easy enough to fix, and can probably be done now, and the code would work with both APIs. This amounts to very little of the code change though.

The second category is going to be the more difficult code changes. The current uses seem very formulaic though, so perhaps they can be collected into helper methods. When it comes time to switch over, we would only need to update the helper methods, not everything that touches them.

The last category is kind of easy, though widespread, and not backwards compatible, so would need to be done when the upgrade happens. It will mostly be global search/replace. As some method names are pretty generic ('Name', 'Value', 'Error', 'Attribute'), we may need to limit the searches. One way is to use whole word matching. I also found using `->Attribute` and `.Attribute` to be faster ways to search/replace for member function names, without modifying similarly named variables.

----

Within NAS2D, only 2 files really make use of XML from a client perspective:
- `src/Configuration.cpp`
- `src/Resources/Sprite.cpp`

Within OPHD, there are many widespread uses of XML.

To avoid breaking downstream projects, I think NAS2D needs to continue to provide XML services. We can perhaps work on abstracting away some of the details, which may allow downstream OPHD changes to become less directly reliant on XML. That will be a slow migration path though.

**Comment by cugone** [comment]
> 
> To avoid breaking downstream projects, I think NAS2D needs to continue to provide XML services. We can perhaps work on abstracting away some of the details, which may allow downstream OPHD changes to become less directly reliant on XML. That will be a slow migration path though.

This is what I ended up doing on my own engine. A couple of `using` declarations to hide the "tinyxml::` namespace and a bunch of free functions that support TinyXML2 but are not required. The most-used services are xml validation, element and attribute parsing, and ForEach-related functions

**Comment by DanRStevens** [comment]
Yes, we should strive to have a simple API for library users that wraps and hide the XML code behind some abstraction. Most of the code I saw (briefly) appears to be using the XML structures for a simple key/value store. If the key/value store part is abstracted, the XML details can be hidden behind it. We could also later on provide alternate backing sources, such as JSON.

Meanwhile, we still need to leave the XML code exposed, so downstream projects have time to adjust to the adapter interface.
