### ISSUE TITLE
Should calls to copy assignment operator throw an exception?

### ISSUE THREAD

**Issue by ldicker83** [lairworks/nas2d-core#24]
Calls to copy an object to itself should be considered a serious mistake. While the program can continue merrily along without blowing up, I'm thinking we should throw some sort of exception to let the user know they have a mistake in their code.

Assuming that we go that route, we need to think of a good name for the exception. Since it can happen in any of the resources only one exception needs to be created for this.

I'm thinking something like `self_copy_assignment`.

**Comment by DanRStevens** [comment]
Can you illustrate this with an example?

Is this more generally about problems involving the [rule of three/rule of five](https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming))?

**Comment by ldicker83** [comment]
```cpp
Image image1("path/to/image.png");
image1 = image1;
```

This is a somewhat contrived example. My thinking was as I was examining the copy operator code and it occurred to me if I should check if the `lhs` parameter is the same as the `rhs`. And in those cases should I just return `*this` or should an exception be thrown to indicate a logic error in the calling code.

**Comment by DanRStevens** [comment]
Sounds like you'd be adding inefficiency to your code to check for accidental inefficiency. I don't think this is even a valid bug check, since the result is likely still correct.

You might give the idea a try, just as a way of scanning for and fixing such inefficiency, though I wouldn't recommend it become part of the code base. It's also an inconvenient scan, since it requires hitting that line at runtime. If there is a compiler warning for such code, which I think there may be, that would be easier, and would work at compile time.

**Comment by DanRStevens** [comment]
I was just re-reading this, and realized I'd recently read something about this exact problem.
https://stackoverflow.com/questions/3279543/what-is-the-copy-and-swap-idiom

The copy-and-swap idiom is a particular way of writing a copy assignment operator. It has strong exception guarantees, and avoids problems with self assignment.

In particular, the accepted answer has note (1) under the "A Failed Solution" section, which seems relevant here.

Perhaps the issue is more about the specific implementation of some copy assignment operators, and it being problematic for self copies? In which case, the copy-and-swap idiom, or concepts behind it, may help.

----

Looking back at your problem example, I assume the problem is more generally like:
```cpp
Image image1("path/to/image.png");
// ...

Image& someImage = ComplicatedComputation(); // return image1; // Well, sometimes anyway
image1 = someImage; // Self-assignment (sometimes)
```

**Comment by ldicker83** [comment]
Ultimately I think I'm overdesigning and overthinking this. It's good to consider but it's a case of this really isn't an issue that will break anything, objects will still be left in a valid state and it just pushes an undue burden onto the library.

Ultimately I'd like to do what I can to de-fat the library -- over time it's gotten a little flabby and this would just be overkill.

Though copy-swap does solve a lot of what may have been running through my mind... so I'll have to consider this a bit more. -_-
