### ISSUE TITLE
NAS2D 2

### ISSUE THREAD

**Issue by ldicker83** [lairworks/nas2d-core#241]
So, I'm thinking about freezing NAS2D as it is and moving on and building a new version based on SDL2 instead of trying to force it the way I've been doing now. I have a little proof of concept code that builds a simple Renderer class that doesn't do much in the way of playing around with OpenGL instead simply relying on SDL2's Renderer interface to handle hardware acceleration.

As I've gotten more and more familiar with NuGet and vcpkg and working on reducing scope of projects, NAS2D has gotten too big and flabby for its own good. The code that was originally built that eventually became NAS2D was started in 2007 with SDL 1.2 -- most of the Renderer interface was built with that in mind including the graphics primitives and assets like Image.

So not to disregard any current work, actually a lot of it could be implemented in a 2.0 type of project.

I've also been thinking about whether or not String and Math libraries really belong in the scope of this sort of project which was originally intended as a way to avoid the boiler plate code of setting up an SDL application. Most of that can be done using SDL2 and a much smaller wrapper class that can be seen in the proof of concept code (going to link it here and make the project public instead of private).

I do like the Signals/Slots idea that NAS2D provides but the original Delegates code it's based on is old and broken and I believe C++17 interfaces can be used instead (though I haven't really looked into it much). I'd almost want to put some effort into redesigning the library and keeping it as close to its original roots as possible -- making it really easy to drop into a new project and just 'go' without having to do all the boiler plate coding in the process.

This is intended as a discussion thread as I could use feedback especially since I'm considering moving OutpostHD away from needing so many dependencies (e.g., if I can get rid of GLEW and PhysicsFS and just stick with the SDL2 packages, get rid of XML dependence in favor of JSON or something else for sprites, etc.)

**Comment by DanRStevens** [comment]
Hmm, sounds like you want to stop and do a rewrite. Understandable, though I would be hesitant to approach things that way. From what I've read, such attempts have a high failure rate, and the reasons are often psychological. When doing a re-write, it's a long process with broken code throughout, which hampers feedback and the sense of progress. It can be very demotivating after the initial excitement wears off, and such attempts usually last much longer than the initial excitement.

With that said, I don't necessarily object to the direction you want to head. I think we can actually get there from working with what we have as a base. I would just suggest doing so incrementally with refactoring.

I would be curious to see if we could get NetGet or vcpkg to work with our own projects. That might provide for faster builds compared to the Git submodule setup. With caching, we would have pre-built dependencies, rather than always having to build dependencies from source. That could speed up builds for OPHD and OP2-Landlord. Though I'd like to point out that currently we don't actually have that figured out. We've never setup package distribution for our own projects, and so have no experience there as of yet.

For Signal/Slots, there is [`std::function`](https://en.cppreference.com/w/cpp/utility/functional/function), which is certainly capable, though is known for being slow. If all you're using it for is click handlers and the like, that shouldn't really matter. Otherwise the delegate stuff you experimented with is likely to be faster. We could also use template methods that accept lambdas for better speed, though the use of templates forces code into header files. We might want to experiment a little and get more experience with the options here.

I would say the number of dependencies is not overly problematic at this time. It's a reasonable number. We can probably remove some. I'm inclined to take an iterative approach to changing that.

If we want to reduce dependencies, and reduce the flab in the library, there are a number of changes we could make to reduce coupling, which would make such a transition easier. For one, the image code could be separated from the file processing code that loads them. That doesn't need to be built into the image class itself. Separating it would allow for easier changes, such as using a JSON based data format.

Finally, OPHD is very far along. I don't think now is the time to go ripping out the rug from underneath. I know it can be tempting, but maybe the desire to redo NAS2D comes from difficulty in finishing up the last bits of OPHD, and the desire to redo NAS2D is a distraction to avoid that last bit of hard work?

**Comment by cugone** [comment]
One way to help the update process is to write a new game. Any features you like can be copied over to "engine side". 

If you're going to write a new version, I'd recommend rolling your own renderer using OpenGL (linux/macOS) and DirectX (windows, OGL on windows is ancient) directly for back-end rendering.

SDL in any form severely limits what's capable in a game. It uses a software renderer and does not allow for batching draw calls nor custom shaders (the fun part of graphics programming!) Trying to have a large number of tiles on screen or, heaven forbid, a particle system, and it will choke.

That said, definitely don't try to recreate it out from under OPHD.  Remake OPHD as OPHD version 2 or something with the intention of rewriting the engine.

**Comment by ldicker83** [comment]
SDL 1 uses a software renderer, SDL 2 is a hardware renderer.

**Comment by cugone** [comment]
Yeah, my bad. I was misinformed with out-dated information. That said, I downloaded and reviewed the source code of SDL2 and the issue with batching and custom shaders still stands.

**Comment by DanRStevens** [comment]
That may be true, but remember OPHD is a turn based strategy. Issues of graphics rendering performance are probably not high on the list of priorities. Much like how my concern about the speed of `std::function` is also probably not high on the list of priorities.

We should probably stop and think about what remains to be done to complete OPHD. Beyond that, what can we do to make development easier to meet that goal. We should probably strive to explicitly avoid things that would be nice to optimize, but won't impact the user experience in any measurable way. Which is something I'm really bad at. I love to nitpick and spend lots of time on rather trivial and small details. Keeps me from having to worry about the big and important tasks, which are usually more difficult to do. You know, the difficult tasks that remind me maybe I'm not quite as smart as I like to think I am. :roll_eyes: 

----

In terms of my priorities for NAS2D, I have 2 main ones:
- Everything builds on all platforms (Windows and Linux as priorities, MacOS because so far it does)
  - Continuous Integration builds happen for all platforms
  - CI builds are fast, feedback on errors and warnings are fast
  - Platform specific code is kept to a minimum, both in the library, and for users of the library
- The library is expressive
  - Common tasks are easy and quick to write code for
  - Low coupling of features, so users can focus on small sections of the library
    - For example, we should be able to use images, without knowing about XML
  - Corner cases are handled gracefully, reducing need for error handling code
  - Calling code is clear without needing comments

So far I feel like I've been focusing on the first part. Most of that is because I develop from Linux, and need a working Linux build to really make a proper contribution to the project. I feel like we're basically there for platform support. There are a number of tasks for the second part I would like to delve into, though they remain a bit fuzzy and abstract at present.

Mostly, I'm happy with the current feature set, and would like improvements that allow for faster development to ease completion of OPHD. Given how far along the game already is, I suspect the feature set is complete enough to support finishing it. I do however get the sense that certain tasks remain a bit onerous.

**Comment by cugone** [comment]
After trying to refactor the Image class I've come to the conclusion that re-writing NAS2D as NAS2D 2 from the ground up as a pure OpenGL 4.x with SDL2 for windowing (GLEW is fine, it's less work than trying to wrangle the function pointers by hand. There are thousands of them.) and DirectX 11 renderer would be much faster than trying to port 12 year old code that is embedded *everywhere*, and frankly, badly in need of updating.

**Comment by DanRStevens** [comment]
If I were an evil galactic overlord, I would probably say something along the lines of:
Your refactoring powers are weak, old man
:wink:

**Comment by DanRStevens** [comment]
This discussion seems to have died down, so I'm going to go ahead and close it. If anyone has more to add, feel free to re-open.

----

My current aim is to continue work refactoring and trimming down NAS2D. I believe we can get to the desired goal through incremental refactoring. I don't plan to participate in a re-write of the library.
