### ISSUE TITLE
Clang 8+ warnings - explicitly defaulted operations are implicitly deleted

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#244]
Clang 8+ (tested with Clang 8, 9, 10) produces a new warning:
```
In file included from src/Mixer/MixerNull.cpp:1:
include/NAS2D/Mixer/MixerNull.h:12:3: warning: explicitly defaulted copy constructor is implicitly deleted [-Wdefaulted-function-deleted]
                MixerNull(const MixerNull& other) = default;
                ^
include/NAS2D/Mixer/MixerNull.h:8:20: note: copy constructor of 'MixerNull' is implicitly deleted because base class 'NAS2D::Mixer' has a deleted copy constructor
        class MixerNull : public Mixer
                          ^
include/NAS2D/Mixer/Mixer.h:171:2: note: 'Mixer' has been explicitly marked deleted here
        Mixer(const Mixer&) = delete;
        ^
In file included from src/Mixer/MixerNull.cpp:1:
include/NAS2D/Mixer/MixerNull.h:13:3: warning: explicitly defaulted move constructor is implicitly deleted [-Wdefaulted-function-deleted]
                MixerNull(MixerNull&& other) = default;
                ^
include/NAS2D/Mixer/MixerNull.h:8:20: note: move constructor of 'MixerNull' is implicitly deleted because base class 'NAS2D::Mixer' has a deleted move constructor
        class MixerNull : public Mixer
                          ^
include/NAS2D/Mixer/Mixer.h:171:2: note: 'Mixer' has been explicitly marked deleted here
        Mixer(const Mixer&) = delete;
        ^
In file included from src/Mixer/MixerNull.cpp:1:
include/NAS2D/Mixer/MixerNull.h:14:14: warning: explicitly defaulted copy assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
                MixerNull& operator=(const MixerNull& other) = default;
                           ^
include/NAS2D/Mixer/MixerNull.h:8:20: note: copy assignment operator of 'MixerNull' is implicitly deleted because base class 'NAS2D::Mixer' has a deleted copy assignment operator
        class MixerNull : public Mixer
                          ^
include/NAS2D/Mixer/Mixer.h:172:9: note: 'operator=' has been explicitly marked deleted here
        Mixer& operator=(const Mixer&) = delete;
               ^
In file included from src/Mixer/MixerNull.cpp:1:
include/NAS2D/Mixer/MixerNull.h:15:14: warning: explicitly defaulted move assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
                MixerNull& operator=(MixerNull&& other) = default;
                           ^
include/NAS2D/Mixer/MixerNull.h:8:20: note: move assignment operator of 'MixerNull' is implicitly deleted because base class 'NAS2D::Mixer' has a deleted move assignment operator
        class MixerNull : public Mixer
                          ^
include/NAS2D/Mixer/Mixer.h:172:9: note: 'operator=' has been explicitly marked deleted here
        Mixer& operator=(const Mixer&) = delete;
               ^
4 warnings generated.
```

**Comment by cugone** [comment]
Looking over `Mixer`, `MixerNull` and `MixerSDL`, the copy constructor was explicitly deleted but Rule of Six was not followed which caused the compiler to implicitly delete the other functions.

Since they are polymorphic in nature, declare the copy constructors as `=delete`d and the move constructors as `=default`d. That should fix the issue.

**Comment by DanRStevens** [comment]
Both very relevant links. The note on slicing was interesting. Before reading that, I was tempted to just remove the declarations from the base class, and leave it to the derived classes to decide.

Why declare the move constructors as `default`, rather than `delete`? I assume in such a case they would normally be deleted.

As per your suggestion, I tried that out in the base class. The compiler still gave warnings. I applied the change to the derived class as well, and that silenced them. Looking at `MixerNull`, I see no particular reason why it shouldn't be copied or moved. Granted, it does contain virtual methods, and there is nothing stopping anyone from creating a more derived class from it and running into trouble with slicing. Failing that though, if more derived classes were disallowed, I don't see any problems with allowing both copy and move for `MixerNull`. Is there a way to do that if the base class has copy/move disabled?

For an abstract base class, do the same rules apply? There should be no way to create an instance of an abstract base class. I assume that would negate concerns about slicing? In this case, the `Mixer` base class is abstract.

**Comment by DanRStevens** [comment]
As per the example in Core Guideline C.67, to prevent slicing, I found that making the base class an abstract type will cause a compile error for line:
```cpp
    auto b2 = b; // oops, slices the object; b2.m() will return 'B'
```

Hence slicing does not seem to be an issue when the base class type is abstract.

This leaves me thinking all special member functions should be `default` in the base class. The derived classes can then choose if it is appropriate to allow copy/move. In the case of `MixerNull`, the class can be declared `final`, and enable `default` copy/move special member functions. For the `MixerSDL` class, we can `delete` the copy operation. I'm a little uncertain now if move operations should be enabled.

----

This discussion also pertains to the similarly designed `Renderer` classes.

**Comment by cugone** [comment]
> 
> Why declare the move constructors as `default`, rather than `delete`? I assume in such a case they would normally be deleted.

It depends on the use case and business logic. If you want to prohibit copying and moving entirely, it makes sense to `delete` all four copy/move functions. Otherwise, preventing copying and making it a move-only type makes sense.

> 
> I'm a little uncertain now if move operations should be enabled.

They most certainly should in nearly every case. You should prefer to allow for moving operations unless the member variable types prohibit it. I.e. If any member variable is non-movable then move operations are silently converted to copy operations.

That said, if you're only passing by reference or pointer, it doesn't matter. There are no copies or r-values being shuffled around.

Hierarchically, prefer copy and move for non-resource-owning types, the default for any user-defined class; prefer move-only for resource-owning types: windows, textures, etc, classes; and prefer disabling all copy/move operations for unique instance types, i,e., a file logger class where a handle to a file is constantly kept open and copying/moving it around would causing things to break. For example, my FileLogger class has all four functions deleted because the user should only ever try to pass it by pointer or reference.
