### ISSUE TITLE
`Filesystem` errors should be reported to caller

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#280]
`Filesystem` errors should be reported to the caller. Right now, errors are logged internally, and then swallowed. This leaves the calling code with no reasonable way of knowing if an error occurred, or if the operation succeeded.

Instead, errors should be reported by throwing exceptions. Logging of errors can then be pushed up into the caller. In particular, this would give control of logging to the users of the library, rather than dictating it within the library itself.

Origin of discussion: https://github.com/lairworks/nas2d-core/pull/243#issuecomment-569457030 

Implications: Most `Filesystem` methods would be able to throw exceptions, and so could not be declared as `noexcept`. In particular, the underlying filesystem is subject to external changes and hardware errors.

**Comment by ldicker83** [comment]
Wasn't the filesystem class throwing exceptions at some point? Maybe it was just a filesystem_not_initialized exception prior (been awhile since I've really looked at it and compared the differences).

Might be good to take advantage of Exceptions -- can leave it as std::runtime_error's or make special derived classes for specific types of exceptions that can still be recovered from or that the caller may want to catch to try a different method or have their application handle in more graceful ways.

**Comment by DanRStevens** [comment]
It throws a few exceptions, mostly `filesystem_not_initialized` (which would be made obsolete by #263).

Currently the code base is an odd mix of logging errors internally, and then ignoring them, or throwing exceptions. We should consistently use exceptions to handle error cases. Particularly when those error cases can impact the caller.

A quick search for `cout` shows mostly error handling code that silently drops errors. The remaining non-error cases are largely tied to `mVerbose`, which should probably be moved off into some unit test. The verbose logging is after all just checking that the system is behaving as expected.

**Comment by ldicker83** [comment]
I pulled mVerbose in favor of conditional compiling for debug output versus release output.

I plan to update the filesytem to throw appropriate exceptions instead of swallowing issues and then returning a pass/fail result. Some functions make sense to return a bool ... e.g., isDirectory() and exists() both make sense to return a bool but a file open, read or write operation should either work or throw if there's an exception. The caller can catch specific exceptions and react accordingly.
