### ISSUE TITLE
Prefer using declarations instead of typedefs

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#316]
`typedef` declarations are commonly declared backwards and are hard to read and remember which is the correct order to declare the "new definition" vs the "old definition". Using declarations were added: `using new_name = old_name;` to prevent these mistakes. They are more clear and describe the intent better and as a bonus can be used with templates and be declared inline unlike typedefs.

**Comment by DanRStevens** [comment]
I would very much welcome this. There are a number of `typedef`s I'm itching to change to `using` aliases. In particular, the Delegate and Signal code has lots of them, and many are quite hard to read. But, I'm waiting until the parameter pack changes are tested and stabilized first. There would be too many merge conflicts otherwise.

Also, we are using C++17 now, and the project has become dependent on that. There is no reason not to use `using` in place of `typedef` now.

**Comment by cugone** [comment]
Adding a ref to examples and "standardize" for type aliasing using `using`.

https://en.cppreference.com/w/cpp/language/type_alias

**Comment by ldicker83** [comment]
I see I'm late to the party, but yes, agreed. typedef's were used before alias's were a thing. Now that they're a thing, that's very much the preferred method.
