### ISSUE TITLE
Windows linking performance message

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#367]
When linking `NAS2D.lib`, the following message is shown on AppVeyor:
```
NAS2D.lib(Filesystem.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
```

----

References:
Microsoft: [`/LTCG` (Link-time Code Generation)](https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation?view=vs-2019)
StackOverflow: [What causes linker warning “MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG”?](https://stackoverflow.com/questions/26279291/what-causes-linker-warning-msil-netmodule-or-module-compiled-with-gl-found-r)

It sounds like there is a discrepancy between how files are compiled, and how they are linked. Would be nice if someone with Visual Studio could look into this. From the StackOverflow answer, it sounds like the relevant settings are:

> - `/GL` is controlled from Configuration Properties > C/C++ > Optimization > Whole Program Optimization
> - `/LTCG` is controlled from Configuration Properties > Linker > Optimization > Link Time Code Generation / Use Link Time Code Generation (/LTCG)
>

**Comment by cugone** [comment]
x86 Debug builds give a different warning:
 - `warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/SAFESEH' specification`

`/SAFESH`: https://docs.microsoft.com/en-us/cpp/build/reference/safeseh-image-has-safe-exception-handlers?view=vs-2019

**Comment by DanRStevens** [comment]
What did you try doing exactly? Did you add Whole Program Optimization to the Debug configuration?

What happens if we remove Whole Program Optimization from Release? Does the message go away? Not sure we want to do that permanently, but it might be interesting to try, just to see what happens.

I suspect this message might only appear for certain configurations, depending on what is changed.

**Comment by cugone** [comment]
> 
> 
> What did you try doing exactly? Did you add Whole Program Optimization to the Debug configuration?

Nothing at the moment. This is a straight pull from master and compile. Whole Program Optimization is turned off by default and the required-to-be-on Link Time Code Generation is unspecified (i.e. off) by default in any build.

Tested with `/LTCG:incremental` and `/GL` flags. Debug builds still show the `/SAFESEH` warning. Additionally a new warning `Not all modules compiled with /Gy- turn off /LTCG:incremental`

Switched back to `/LTCG` and `/GL` flags for all configurations and all builds. The only remaining warning is for the `test x86 Debug` build and it's the `/SAFESEH` warning.

> 
> What happens if we remove Whole Program Optimization from Release? Does the message go away? Not sure we want to do that permanently, but it might be interesting to try, just to see what happens.
> 
> I suspect this message might only appear for certain configurations, depending on what is changed.

It's off by default. Turning it on is what's different. The issue is it's on for `NAS2D Release` and off for `test Release` builds and that's what causes the warning in `test Release` builds.

Turning `/GL` and `/LTCG` on for `test Release` builds and off for `test Debug` builds makes all except the `ignoring /EDITANDCONTINUE due to /SAFESEH` warning in `test x86 Debug` builds go away.

The `ignoring /EDITANDCONTINUE due to /SAFESEH` warning is due to a global per-machine Visual Studio Debugging option `Enable Edit and Continue` along with certain project settings turned on.

Ref: https://devblogs.microsoft.com/cppblog/c-edit-and-continue-in-visual-studio-2015-update-3/

Since those project settings should never be turned on due to compiling optimizations (incremental linking, and minimal rebuild), there's no reason to have Edit and Continue ever turned on.

Turning off Edit and Continue fixes the issue. Along with the above changes to Release, all warnings go away.

**Comment by DanRStevens** [comment]
Ok, I'm having a little trouble following all that. Would you be able to make the needed change?

**Comment by cugone** [comment]
@DanRStevens 

I've added a tl;dr. :)
