### ISSUE TITLE
Redirect all intermediate visual studio output to "Temporary" or "Intermediate" folder

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#375]
It's a pain to do a complete fresh clean and rebuild of the project. Running "Rebuild Solution" doesn't catch everything so it's easier and safer to just delete the intermediate files. The problem is, they are scattered among several different folders and it would be much easier to just delete one root folder and you get a fresh compile immediately.

Similarto linux's `.build` folder, this can be solved by redirecting the intermediate file output to a single folder then further subdirectories split it up by `projectname_configurationname_platformname`. Simply deleting the toplevel (`/proj/vs2019/Temporary` or `proj/vs2019/Intermediate` in Unreal Engine speak) folder will cause a full rebuild of the project/configuration the next time the source is built.

**Comment by DanRStevens** [comment]
I like the idea of having everything under one subtree.

One question I have, is if this impacts downstream projects. I know some projects will change output name based on build settings, rather than use an identical filename, but a different folder name. Like how the static libraries for Google Test are either `gtest.lib` (`Release`) or `gtestd.lib` (`Debug`). I'm wondering if an alternate folder will cause issues during linking of downstream projects, or require them to add additional configuration settings.

I have a feeling Visual Studio will correctly handle different output folders, and feed through all the needed settings.

**Comment by cugone** [comment]
It's a change to `$(IntDir)`, the Intermediate Directory, and doesn't affect the Output directory `$(OutDir)` which is where output files are stored nor the output name (`Target Name` in visual studio) which is what the `.exe` or `.lib` is named. 

I'm recommending a change to `$(SolutionDir)Temporary\$(ProjectName)_$(Platform)_$(Configuration)\`

I noticed that the `test` project specifically uses `x86\$(Configuration)` instead of `$(Platform)\$(Configuration)`. I forget, is this an AppVeyor-required usage?
