### ISSUE TITLE
Prefer std::map::find instead of std::map::operator[]

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#380]
Using `std::map::operator[]` is error prone and easy to use incorrectly as a key already exists is silently overwritten and one that doesn't exist is silently added to the map; this is especially problematic when dealing with strings as keys or value types that shouldn't be copied or overwritten.

Prefer instead to use `std::map::find(...)` to detect bad keys.

Facebook has a really good talk about it from CppCon: https://www.youtube.com/watch?v=lkgszkPnV8g&t=7m3s

I've linked to the relevant portion of the talk, but I recommend watching the whole thing. 

And here's some example code:

BAD:
```
std::map<std::string, Thing*> things;
//...
Thing* GetThingByName(const std::string& name) {
    return things[name];
}
```

GOOD:
```
//Get Thing
std::map<std::string, std::unique_ptr<Thing>> things;
//...
Thing* GetThingByName(const std::string& name) {
    const auto found_iter = things.find(key);
    if(found_iter == std::end(things)) {
        //Thing not found. Log error.
        return nullptr;
    }
    return *found_iter->second;
}
//...

Thing* CreateThing(const std::string& name) {
    auto new_thing = std::make_unique<Thing>(name);
    auto thing_ptr = new_thing.get();
    things.try_emplace(name, std::move(new_thing)); //try_emplace won't do anything if the key already exists.
    return thing_ptr;
}


Thing* GetOrCreateThing(const std::string& name) {
    if(auto* thing = GetThingByName(name)) {
        return thing;
    }
    return CreateThing(name);
}
```

**Comment by DanRStevens** [comment]
We might also want to consider using `at`, which throws `std::out_of_range` if the key isn't found. That way we could make use of exception handling for errors, rather than having to check return codes.

References:
[`std::map::operator[]`](https://en.cppreference.com/w/cpp/container/map/operator_at)
[`std::map::at`](https://en.cppreference.com/w/cpp/container/map/at)
[`std::map::find`](https://en.cppreference.com/w/cpp/container/map/find)

Behaviour when a key doesn't exist:
- `operator[]`: Insert new key
- `at`: Throw exception
- `find`: Return sentinel error value (`end()` iterator)

----

Might be good to mention some specific code that uses `std::map::operator[]`. Particularly since `[]` isn't super easy to search for. I see uses of `std::map` from code in the `Resources` folder, such as `Music`, `Font`, `Image`, as well as in `RendererOpenGL`.
