### ISSUE TITLE
Add center_x/center_y functions to Font

### ISSUE THREAD

**Issue by ldicker83** [lairworks/nas2d-core#40]
In keeping things cohesive across the entire interface, center_x()/center_y() functions should be added to the Font class. This eliminates the need for code such as:

```cpp
Font fnt("some_font.ttf", 14);
Utility<Renderer>::get().drawText(fnt, "Some Text", (fnt.width("Some Text") / 2) + 100, (fnt.height() / 2) + 100, 255, 255, 255);
```
This basically centers the font around a point and is a surprisingly common function, much like Rectangle's and the screen itself. The above code with the improvements will look as such:

```cpp
Font fnt("some_font.ttf", 14);
Utility<Renderer>::get().drawText(fnt, "Some Text", fnt.center_x("Some Text") + 100, fnt.center_y() + 100, 255, 255, 255);
```
This is mostly a readability improvement and a convenience function.

**Comment by DanRStevens** [comment]
I was just thinking, fonts are often positioned by the [baseline](https://en.wikipedia.org/wiki/Baseline_(typography)). You may have other needs here, but I thought I'd mentioned it just in case.

**Comment by ldicker83** [comment]
True -- in this case the baseline is considered the 'bottom' of the font so the center function goes by the height of the font not including the drop (I can't for the life of me remember the names of all the different parts anymore)... so basically it does this via the baseline.

Good point though.

**Comment by DanRStevens** [comment]
While refactoring to use vectorized operations I saw many lines of code use the general pattern mentioned in this issue:
```cpp
renderer.drawText(font, "Some Text", {100 - (font.width("Some Text") / 2), 100 - (font.height() / 2)}, NAS2D::Color::White);
```

I was tempted to add a `Font::size(std::string_view text)` method, which would return a value equivalent to `NAS2D::Vector{font.width(text), font.height()}`. Then you could center text using the offset `font.size(text) / 2`.

```cpp
renderer.drawText(font, "Some Text", NAS2D::Point{100, 100} - font.size("Some Text") / 2, NAS2D::Color::White);
```

That may make a little more conceptual sense than `center_x` and `center_y`, since you offset using a `NAS2D::Vector`, while "center" would generally be represented by a `NAS2D::Point`.

**Comment by ldicker83** [comment]
This use would help with the overly verbose code which was the motivation for the `center_` functions. That would effectively close this issue and provide a consistent interface.
