### ISSUE TITLE
Add MathUtils::RangeMap

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#416]
Related: #415 

This will make is way easier to map one range of values to another. E.g. Mapping a normalized slider value to SDL_mixer's minimum and maximum volume values.
```
RangeMap(value, 0.0f, 1.0f, 0.0f, 128.0f);
```

**Comment by DanRStevens** [comment]
Sounds like you want to implement *linear scaling*. I suppose we might consider other types of scaling in the future as well. I think that term might be more clear too, since when I read RangeMap I think a function that does some kind of lookup or table based substitution.

This operation generalized to multiple data types. It may be reasonable to use a template method to implement this. There might even be a different between the input and output types.

----

As for where this will be used, I'm not completely sold that's the way we want to go. Maybe we just want to stick with integer values. The slider control should also give some thought as to how it should be implemented, in terms of the data type and possible values it can take on. An integer solution may appear to be cleaner from a mathematical perspective.

**Comment by cugone** [comment]
Mapping `[0.0,1.0]` to `[0.0,128.0]` was just an example. This allows mapping `[-1,1]` to `[0,255]` just as easily.

**Comment by DanRStevens** [comment]
As another example, it could be used to map the slider's size in pixels to the range `0..128`. :wink:

Still a potentially useful method.
