### ISSUE TITLE
Add central Random Number Generation

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#453]
See: https://github.com/OutpostUniverse/OPHD/pull/167#discussion_r373833780

For performance, thread- and network safety, there should be no more than one place random numbers are generated.

Cherno has a good [video](https://www.youtube.com/watch?v=PPup1yeU45I&t=11m30s) on it. I've jumped to the relevant timestamp. He tends to ramble.

**Comment by DanRStevens** [comment]
There was a bit of external discussion on this issue. I had suggested using `inline` variables in a header file, rather than the singleton pattern. I believe that would be a low boilerplate way of generating random numbers from a shared global generator.

I had also suggested raw access to the standard library random number generators, with no wrapper layer. I figure the standard library has sufficient support that generating random numbers in specific ranges is quite easy, and any wrapper would just be one line methods anyway. Additionally, it's probably better for people to learn and use the standard library, rather than a custom wrapper.

I had also suggested this be an app level concern, rather than a library level concern. There are sometimes rather specific app level concerns for random numbers, so perhaps it should be left to the app to decide how things should work. This is particularly true of seeding the random number generator in specific ways, or capturing random number state to be serialized to a saved game file or reply file. Related to that, there are currently no uses of random numbers within the NAS2D library itself, so we don't really need random number support within the library.

Based on these suggestions, it seems likely further work will continue in the OPHD repository, rather than the NAS2D repository.

----

References:
https://github.com/lairworks/nas2d-core/pull/454#issuecomment-584486663 Centralized Random Number Generation
#455 Remove Utility class
StackOverflow: [How do inline variables work?](https://stackoverflow.com/questions/38043442/how-do-inline-variables-work)

**Comment by cugone** [comment]
There is also using Noise-based Random Number Generation, this implementation is faster than `std::mt19937`, and has zero state so there's no memory usage so there's no reason to keep an instance around: https://www.gdcvault.com/play/1024365/Math-for-Game-Programmers-Noise
