### ISSUE TITLE
Remove Utility class

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#455]
Ref: https://github.com/lairworks/nas2d-core/pull/454#issuecomment-584486663

**Comment by DanRStevens** [comment]
To aid lookup, the comment referenced above is:

> A singleton in and of itself isn't really useful. You can always just create only one object of any given type. There are even plenty of people who view singletons as an anti-pattern:
> [Why Singletons are Evil](https://docs.microsoft.com/en-ca/archive/blogs/scottdensmore/why-singletons-are-evil)
> [Singleton Considered Stupid](https://sites.google.com/site/steveyegge2/singleton-considered-stupid)
> [Patterns I Hate #1: Singleton](http://web.archive.org/web/20120603233658/http://tech.puredanger.com/2007/07/03/pattern-hate-singleton)
> [Root Cause of Singletons](http://misko.hevery.com/2008/08/25/root-cause-of-singletons/)
> 
> If what we really have is global state, then why not just declare a global, and let the game designer agree to only use their one instance.
> 
> Which is perhaps also why I think this should be in the game rather than the library. You don't want global state in the library.
> 

----

This issue of course correctly identifies that `Utility` is just implementing the Singleton pattern in a generic way for any class.

As the pattern itself is suspect, we may want to revisit this code. I suspect there is plenty of potential for refactoring to improve the code. Eliminating the Singleton nature of classes would force us to consider how access to those classes is obtained, which may also help force us to consider the interfaces we need to support to allow proper access.

To be clear, we can't simply rip out the `Utility` template. We need to refactor first before that can become a consideration.

Two of the major classes that are used in a Singleton manner are `Renderer` and `Mixer`. We may want to start with refactoring those classes first before trying to address changes involving `Utility`.

----

In the end, the game (rather than the NAS2D library) may end up with a header file declaring [`inline`](https://en.cppreference.com/w/cpp/language/inline) global variables (C++17). The `Renderer` and `Mixer` objects would then be global objects, rather than wrapped in `Utility`.

Of course, there is runtime support for setting which Renderer or Mixer to use, so those globals may need to be a pointer or reference type.

**Comment by cugone** [comment]
One way to help things along is to force NAS2D to use dependency injection. That way it has no knowledge of any global variables the downstream games may declare, including Utility.

It's a big undertaking but will be worth it in the long run.

**Comment by DanRStevens** [comment]
I was thinking similar, but I don't know if we want to go all the way on it. We might still want to have global variables in the end.

It might be good if some parts of the code could take a parameter though. I guess we'll need to see how widespread the uses are, and how burdensome adding potentially lots of parameters would be.

**Comment by DanRStevens** [comment]
From external discussion, the following video was quite relevant:
[Retiring the Singleton Pattern - Peter Muldoon - Meeting C++ 2019](https://www.youtube.com/watch?v=f46jmm7r8Yg)

----

According to the video, the `Utility` class does not imply Singleton. The Utility class provides a single global instance of any given type. There are no restrictions on instantiating the classes outside the scope of the `Utility` template, hence the classes are not actually restricted to single instances, and so are not real Singletons.

Instead, what we really get are a "handy" grab bag of global variables that don't need to be feed through potentially deep levels of function calls. Effectively, all we really have is a global. As such, we could potentially just use globals. In particular, we can use `inline` header variables to access globals.

----

In the StackOverflow answer [How do inline variables work?](https://stackoverflow.com/a/38043566/5333629), there is discussion of linker support needed to support `static` variables in templates. The example template code exactly matches the pattern used by the `Utility` class. The answer states the linker support needed by the language to do this is the same mechanism that is now accessible through `inline` variables, which may be placed in header files. This is further indication we should perhaps use `inline` variables instead.

**Comment by DanRStevens** [comment]
Adding cross repository reference to related issue: https://github.com/OutpostUniverse/OPHD/issues/253
