### ISSUE TITLE
XmlElement::attribute(const std::string&, int) allows empty std::string's

### ISSUE THREAD

**Issue by ldicker83** [lairworks/nas2d-core#780]
Empty strings passed to this functions should be treated as incorrect use and throw an exception.

**Comment by DanRStevens** [comment]
It's not super clear to me if the bug is within this method, or the caller of this method.

Passing a non-empty string might be considered a documented restriction that leads to undefined behaviour, much like many methods assume a pointer parameter is non-null. It's not compiler checked, and can lead to a hard crash, though it's often considered the caller's responsibility to ensure they don't make an invalid call.

I'm not sure the XML spec allows for attributes with empty names, though conceivably, such a thing could be allowed. Particularly if the name allowed for any kind of quoting. Though this is really a minor point.

A more interesting point is what happens if you change the output format to something like JSON, or some other format, perhaps yet to be developed. Would an empty string necessarily be an error there too?

**Comment by ldicker83** [comment]
I noticed it when I accidentally passed an empty name for an attribute and it still wrote the value out and then promptly crashed. I would consider it a bug as it blindly accepting it. This should probably through an exception to let the end user know that they are using it wrong.

I would imagine that any sort of data serialization format should consider an empty attribute name to be incorrect since attributes are accessed by name. I'm not sure if json operates solely on the principle of data as a structure such that how data is laid out also dictates its structure but I would imagine even in that case an empty attribute name should be considered wrong.

**Comment by DanRStevens** [comment]
I believe JSON is capable of empty attribute names:
```
{ "" : "Hello world" }
```

Seeing as how you can do a string comparison to test for equality with `""`, I don't see that as being a problem.

----

I'm not sure how it would look with XML though, since only the values tend to be quoted. I'm not sure attribute names can be quoted, or if any such quotes would be considered part of the name, or if it would be considered a parse error:
- `<XmlTag ""="HelloWorld" />`  (valid? Empty attribute name, or attribute name of `\"\"`?)
- `<XmlTag ="HelloWorld" />`  (valid? Empty attribute name)

It seems less likely that XML would support empty attribute names, though I'd need to check a reference to be sure.

----

Whether attribute names can be empty or not may be file format specific. That goes beyond just XML/JSON/whatever. When you get to end program specific file formats, there may be additional restrictions imposed, such as the names and structure of tags, including if any of the allowed names are empty.

**Comment by ldicker83** [comment]
`<XmlTag ="HelloWorld" />` is how it ends up looking which leads to failure during loading/parsing, something along the lines of 'malformed' (it was all of 24 hours ago now that I was looking at it and I can't remember what it was whining about).

**Comment by DanRStevens** [comment]
Another consideration is we should be getting close to removing TinyXML from direct project inclusion, and will soon be moving towards `vcpkg` to provide TinyXML/TinyXML2. Any custom changes made directly to the TinyXML library code will be lost at that point.

Next task on my list is to complete the `Configuration` refactor, which is followed by reworking the `Sprite` XML processing code, reworking the OPHD XML processing code (a bit of a larger task), and then finally removing direct inclusion of TinyXML and switch to `vcpkg` to provide TinyXML.

**Comment by DanRStevens** [comment]
I would like to close this as something we won't fix.

If empty attribute names are a problem, perhaps they can be addressed at a higher level, rather than in the XML library itself. The plan is to move to TinyXML2, and to include it using `vcpkg`. As such, it won't be possible/feasible to apply custom patches to the XML library code.

**Comment by ldicker83** [comment]
That's fair enough. I'll go ahead and close this issue as wontfix.
