### ISSUE TITLE
Consider separating SDL from package management

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#890]
I'm starting to dislike SDL integration through vcpkg, (or any package manager) as it hijacks the declaration of `main` globally in all VS solutions and projects even if they are unrelated to the project that actually needs it due to how vcpkg works. It fundamentally breaks `WinMain` projects as well.

Is there a way to add the required files to a Thirdparty folder and manually compile SDL in? It'll add a maintenance step whenever SDL adds new features that you may want to take advantage of, but It's not that hard to copy-paste the source code.

**Comment by DanRStevens** [comment]
The hijacking of `main` has nothing to do with `vcpkg`. That's part of SDL. In the header, it redefines `main` so it can hijack it:
```cpp
#define main SDL_main
```

Regardless of how we install and use SDL, that will still be an issue. In particular, Linux uses the `apt` package manager to install SDL, and it has the same issue (#889). You can partially avoid it by not including the SDL header from your `main.cpp`, however you also need to avoid adding compiler flags such as `-Dmain=SDL_main`, which defines that same macro from the command line. That means being careful about how `sdl2-config` is used, since it may define that macro by default.

I recommend we close the case.

**Comment by DanRStevens** [comment]
Some relevant material, in case you're interested:
https://stackoverflow.com/questions/11976084/why-sdl-defines-main-macro

**Comment by cugone** [comment]
The global installation via vcpkg does affect unrelated projects though because it's system-wide. I think that's my main issue with it. If you can reduce the scope of its changes to just the relevant projects I wouldn't be as concerned.

**Comment by cugone** [comment]
In fact, the "feature" can be turned off with a small bit of code:

https://wiki.libsdl.org/SDL_SetMainReady

```cpp
#define SDL_MAIN_HANDLED
#include "SDL.h"

int main(int argc, char *argv[])
{
    SDL_SetMainReady();
    SDL_Init(SDL_INIT_VIDEO);

    ...

    SDL_Quit();

    return 0;
}
```

**Comment by DanRStevens** [comment]
Sounds like there are other reasons for wanting to move away from `vcpkg`.

I have been meaning to look into [Chocolatey](https://chocolatey.org/), though I don't know if it would be any different.

In particular, I've been pondering switching the Windows CI builds from AppVeyor to CircleCI, so that all platforms can be handled with a single CI provider. The current Windows image on CircleCI doesn't have `vcpkg` installed, but I believe it does have Chocolatey.

----

The `SDL_main` discussion should probably be part of #889.

**Comment by DanRStevens** [comment]
I looked a bit into Chocolatey. It seems more geared towards installing end user programs, not developer libraries. I didn't see any packages available for SDL/SDL2, nor for TinyXML. Looks like that idea was a bit of a dead end.

**Comment by DanRStevens** [comment]
I think we may need to update the title of this issue, and perhaps redefine the scope. I believe the major point was:
> The global installation via vcpkg does affect unrelated projects though because it's system-wide. I think that's my main issue with it. If you can reduce the scope of its changes to just the relevant projects I wouldn't be as concerned.

I suppose end users could potentially choose to use `vcpkg` without system wide integration, which might solve that immediate need, though could add extra environment setup each time a developer works on the project on such systems.

Outside of that, I'm not entirely sure what can be done. We're not exactly willing to walk away from package management, there are just too many benefits. So unless I'm missing something, there doesn't seem to be any clear actionable steps we can take on our end for this. Without something clear to do on our end, I'm thinking we should close this issue.

**Comment by cugone** [comment]
> 
> 
> I think we may need to update the title of this issue, and perhaps redefine the scope. I believe the major point was:
> 
> > The global installation via vcpkg does affect unrelated projects though because it's system-wide. I think that's my main issue with it. If you can reduce the scope of its changes to just the relevant projects I wouldn't be as concerned.
> 
> I suppose end users could potentially choose to use `vcpkg` without system wide integration, which might solve that immediate need, though could add extra environment setup each time a developer works on the project on such systems.

Correct. Requiring system-wide integration of vcpkg is the issue. If there's a way to make it project-only such that it doesn't interfere with other visual studio projects and only runs when compiling nas2d or ophd that would be great.

**Comment by DanRStevens** [comment]
Do you mean to say that other projects which don't depend on SDL are being compiled with SDL, and having their `main` method hijacked?

**Comment by cugone** [comment]
> 
> 
> Do you mean to say that other projects which don't depend on SDL are being compiled with SDL, and having their `main` method hijacked?

Yes. :)

**Comment by DanRStevens** [comment]
This might be relevant:
[I can't use user-wide integration. Can I use a per-project integration?](https://vcpkg.readthedocs.io/en/latest/about/faq/#i-cant-use-user-wide-integration-can-i-use-a-per-project-integration)

Tagging #373 as related.

**Comment by cugone** [comment]
See #952 update to [ReadMe ](https://github.com/lairworks/nas2d-core#readme) for workaraounds.
