### ISSUE TITLE
Streaming binary data

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#917]
Streaming binary data in-memory and to/from a file will improve loading/saving times of custom types.

Since the layout of the built-in and base engine types is known at compile-time and most types can be built as composites of those types templating the code is trivial and downstream projects can build upon the engine types to make their game-specific types serializable to/from binary.

I have some old code sitting around that can stream types to/from binary for reference and it is endian-aware for host order:

https://github.com/cugone/GGE1.0/blob/master/Code/Engine/Core/FileUtils.hpp
https://github.com/cugone/GGE1.0/blob/master/Code/Engine/Core/FileUtils.cpp

C++20 is supposed to have a [`std::endian`](https://en.cppreference.com/w/cpp/types/endian) type but that's a small part of endian-aware streaming.

**Comment by DanRStevens** [comment]
I've traditionally also been a fan of binary data formats. You're right in that they're faster to process, and often take less code to implement.

There's was some earlier discussion with Leeor about supporting stream processing. Way back, Leeor had mentioned the idea of borrowing the stream code from the [OP2Utility](https://github.com/OutpostUniverse/OP2Utility) library project. That code was much more focused on binary than text. It had a number of template methods that could auto serialize all primitive types, and structs of primitive types. It also had a bit of support for serializing variable sized containers and strings. In that case it would use a length prefixed format, and you could specify the type for the length prefix, allowing for compact strings with a single byte length prefix, or larger collections with perhaps a uint32_t sized prefix.

I took a brief look at your library. It seemed similar in general concept. I noticed you used the same template trick to handle writing of simple data types. One caveat I'd like to bring up is that not all data types are safe to copy using `memcpy`, and so are also not safe to copy through serialization using a `memcpy` style approach. An example would be classes with private fields, and non-trivial constructors/destructors. You can avoid such problems by guarding the serialization methods with `std::is_trivially_copyable` on the template type.

A bonus of the `std::is_trivially_copyable` guard is that you can then write a separate specialization for containers, which are not trivially copyable.

I have mixed feelings about endian correction. There are rare cases where you might not want system dependent correction. It's something I've generally preferred being done at a higher level, so the programmer has more control over it. An endian converting stream wrapper object would be a fairly simple and lightweight way to perform endian correction, and have it done separately from the rest of the serialization, thereby giving the programmer more control over it. Also, as I've noticed in your library code, there was quite a bit of custom specializations to handle aggregate data types, as it's not simple to correct the endianess of each field without custom decomposition functions.

----

Anyway, with that said, there's also been some discussion about staying with the text format data files. They are quite easy to manually check during development, and easy for new people to understand and potentially made modifications to.

Another benefit of the text format, is they support extension in a fairly natural way, which is handy when the file format is still in flux. We still add fields to structures, and provided they have a reasonable default when not specified, it's quite easy to extend the file format without invalidating old data. That's much more awkward to do with binary data. As serialization is often done raw on structs, you often end up with multiple struct definitions to cover all the previous versions of the data format.

As for performance, there are really no performance concerns about the current data file processing. I haven't noticed any significant processing delays during loading or saving. If performance was the main motivator, it would be a pretty low priority item.

Finally, as worded, it's not super clear if this issue is about support for binary stream processing, or about actually changing the current data formats. I assume it's about the support, since the issues was opened against NAS2D, rather than OPHD. Most of the current data formats are controlled by OPHD, rather than NAS2D. Being a library, we've tried to avoid specifying formats in NAS2D, particularly binary formats, and where we've failed at specifying data formats (like the `RendererOpenGL` and `MixerSDL` settings loading code), there is a general desire to push that down to the app and remove it from NAS2D at some point in the future.

**Comment by cugone** [comment]
> 
> ...One caveat I'd like to bring up is that not all data types are safe to copy using `memcpy`, and so are also not safe to copy through serialization using a `memcpy` style approach...
> 
At the time it was written, `BinaryStream` was an ADT and only provided an interface, The only completed implementation was `FileBinaryStream`. I'm not sure if it's the same as `memcopy`, but `FileBinaryStream` used the C functions `fread` and `fwrite` internally.

> A bonus of the `std::is_trivially_copyable` guard is that you can then write a separate specialization for containers, which are not trivially copyable.
> 
I will be using the `std::is_trivially_copyable` trick in the future until concepts come along. :) As-is, the code doesn't because any non-built-in type was intended to have its own template override and even then limited in scope to engine types. We never got around to implementing custom-for-this-game-only types.

> I have mixed feelings about endian correction....
> 
I do too, but the code was written for interfacing with Networking code that needed the feature.

> Anyway, with that said, there's also been some discussion about staying with the text format data files. They are quite easy to manually check during development, and easy for new people to understand and potentially made modifications to.
> 
> Another benefit of the text format, is they support extension in a fairly natural way, which is handy when the file format is still in flux...
>
I agree on ease of debugging, comprehension, and extension. For small types, text is trivial; but: Things like models always perform better with binary packed files due to sheer volume of data; A "small" area of 100x100 tiles is actually quite big in terms of data and can benefit from RLE binary encoding, especially if there are large blocks of the same tile and multiple layers. By that point you really have *multiple* tens of thousands of tiles and trying to load all of that from text is going to show a performance hit.

My MineCraft clone had world chunks of 15x15x128 (28,800) blocks and that was binary RLE encoded to/from disk in real time on top of generating new ones on-the-fly.
 
> Finally, as worded, it's not super clear if this issue is about support for binary stream processing, or about actually changing the current data formats....
> 
It was about adding support.

> Most of the current data formats are controlled by OPHD, rather than NAS2D....
That's kinda-sorta backwards. Games should inform the engine "Hey this might be a good feature to add to the engine to benefit all future games." and then after reviewing the feature, elevating it to engine-side rather than outright "If it's not in this game, the engine doesn't need it."

I'll use Unreal as an example since things like CryEngine, Source/Source2 (et. al) are proprietary:
- Make a game, say, Fortnite, in Unreal Engine 4;
- Add features like enhanced lighting, physics, and large-world streaming of static meshes;
- Realize this would make the engine better;
- Add features to engine;
- Release Unreal Engine 5.

(Granted, some changes between UE4 and UE5 were due to preferring in-house implementations over paying licensing fees for a technology...)

Epic almost always adds new features to the engine in response to a game in development. Optimizing or bug-fixing already-established features is an on-going process.

**Comment by DanRStevens** [comment]
All of `memcpy`, `fread`, and `fwrite` do byte by byte memory copies. They can be made to work on object addresses, even if the objects have `private` fields, and accessor methods to ensure the private data maintains some kind of invariant. By using a byte by byte copy, you bypass those protections and gain access to the internal data (and in a compiler and configuration specific format). This has the potential to break invariants and cause undefined behaviour.

Consider for a moment what would happen if you tried to raw serialize a `std::string`. The `std::string` object doesn't contain the string data directly (assuming no small string optimization), but rather has a pointer to the data, and perhaps fields to indicate the length of the string, or the length of the buffer so it knows how much can be stored before re-allocating storage. If you raw serialized a `std::string`, you'd be accessing those bookkeeping variables, and not the character data. If you overwrite the string pointer, or the size of the buffer, you've violated a class invariant which could lead to unsafe behaviour when later reading or writing to the `std::string` object.

Classes that maintain invariants through constructors/destructors, accessor methods, or private data, such as `std::string` would fail to be [`std::is_trivially_copyable`](https://en.cppreference.com/w/cpp/types/is_trivially_copyable).

> Objects of trivially-copyable types that are not potentially-overlapping subobjects are the only C++ objects that may be safely copied with `std::memcpy` or serialized to/from binary files with `std::ofstream::write()`/`std::ifstream::read()`.

See definition of [TriviallyCopyable](https://en.cppreference.com/w/cpp/named_req/TriviallyCopyable) for more info.

----

Currently OPHD only serializes tiles that have been modified from the base map, so very few tiles actually get read or written in text format. Maybe that will change as the game nears release and colony sizes get larger?

----

I think the point was more that designs aren't always perfect right from the start. And sometimes you just need to get started and have something to look at, and a bit of experience, before you can really reason about the right design. I think OPHD was started with more of an ethos of get something working, and maybe make it nicer later on down the road. Lately I've been focusing on trying to make things nicer. That means revisiting some of the assumptions that lead to where code was originally placed, and adapting to changing requirements. Much of those designs made sense for where things started, and got the project to where it is today, but maybe don't entirely make sense for where we want to take it.
