### ISSUE TITLE
Use `std::filesystem::path` instead of `std::string` for filepath arguments

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#973]
Various Resource classes and other files use `std::string` to represent file paths. These should be changed to `std::filesystem::path` types which can accept plain names as well, particularly if stored in a `std::map` that accepts `std::string` as the key.

Path corrections like canonicalizing or converting to absolute versions, and converting to the preferred slash type to make the keys consistent for searching may be required before storing.

**Comment by ldicker83** [comment]
Generally speaking I agree with this but I want to be sure this will work on macOS builds without breaking. Apple has an annoying habit of lagging behind adopting updated standards.

**Comment by DanRStevens** [comment]
Related, we'll probably want to use [`std::filesystem::path::extension`](https://en.cppreference.com/w/cpp/filesystem/path/extension) and such internally to break apart components of paths (think `extension` and `parentPath`). Or perhaps just always return strings as `path` objects, and let the caller call standard library methods to extract those values.

**Comment by DanRStevens** [comment]
I was looking back at this issue. I noted one small compatibility issue, in that appending path components will need to use `operator /` rather than `operator +`. Example:
```cpp
filesystem.mountSoftFail(filesystem.basePath() / "data");
```

That compatibility issue is only likely to affect maybe one or so lines of projects that use the library.

----

The argument type change would require moving the `<filesystem>` include from `Filesystem.cpp` file to the header file. That means extra transitive includes. It might be wise to gain some timings for compile times before and after the change. Some standard library headers can result in a lot of (transitively) included code, which can negatively impact compile times. Based on `-ftime-report`, we spend almost 80% of the compile time on source code parsing, and a large part of that is transitive header includes. I'm guessing the effect of this particular library will be fairly minor though. Besides, it doesn't look like `Filesystem` is widely included, and it's always included from cpp files.

I suppose the other side of moving the include to the header is we effectively leak more details about the implementation. I think that's really what's on my mind, though is probably a pretty minor point.

----

We may want to define which types should use `std::filesystem::path`. For raw filesystem paths, we probably want to use `std::filesystem::path`, such as for the `mount` calls. For virtual filesystem paths, such as `readFile` and `writeFile`, maybe, maybe not. We are not strictly required to use paths in the same format within the virtual filesystem, though the way we implement things, they're just appended to real filesystem base paths, so will have the same format. This is maybe getting back to that point about leaking implementation details.

I'm kind of thinking of changing all paths to `std::filesystem::path`, though maybe we'll want to split the changes so the virtual filesystem paths are changed in a separate commit.

I have working test code for the first half of those changes.

**Comment by DanRStevens** [comment]
So the "working" test code didn't work when compiling for Windows.
https://github.com/lairworks/nas2d-core/actions/runs/3180105984/jobs/5183302136

It seems on Windows the `std::filesystem::path` object is not implicitly convertible to `std::string`, while on Linux and MacOS it is. This impacts some of the unit test code for path checking, which assumes implicit conversion to `std::string` in some of the Google Test matchers.

The unit test code issue can be worked around by updating the checks to use explicit conversions to `std::string`. In particular, Google Test has `Truly` which can take a lambda expression. This perhaps allows for better, more precise checks, with more descriptive names.

Support lambdas:
```cpp
constexpr auto EndsWithDirSeparator = []() {
	return testing::Truly([](const auto& path) { return path.string().ends_with("/"); });
};


constexpr auto HasPartialPath = [](const auto& subString) {
	return testing::Truly([&](const auto& path) { return path.string().find(subString) != std::string::npos; });
};
```

Example usage in unit tests:
```cpp
TEST_F(Filesystem, prefPath) {
	// Result is a directory, and should end with a directory separator
	EXPECT_THAT(fs.prefPath(), EndsWithDirSeparator());
	EXPECT_THAT(fs.prefPath(), HasPartialPath(AppName));
}
```

It's also possible to nest the result of the lambdas:
```cpp
	EXPECT_THAT(pathList, Contains(HasPartialPath(AppName)));
```

**Comment by cugone** [comment]
> It seems on Windows the `std::filesystem::path` object is not implicitly convertible to `std::string`, while on Linux and MacOS it is. This impacts some of the unit test code for path checking, which assumes implicit conversion to `std::string` in some of the Google Test matchers.
> 

That's because the `native` string type implementation internal to `std::filesystem` in MSVC is `std::wstring`; on GCC and Clang it's a regular ol' `std::string`. You can't convert between them without an intermediary/explicit conversion via the `std::filesystem::path::string()` and `std::filesystem::path::wstring()` functions.

See a [godbolt example](https://godbolt.org/z/eY4Kd39of) of implicit/explicit conversions working (...and not)

**Comment by DanRStevens** [comment]
Ahh, ok, that makes a lot of sense.

I suppose I haven't looked too closely into how `std::filesystem::path` is implemented. It's curious how the internal type leaks out in terms of allowed implicit conversions. I'm wondering now if there was explicit support for the conversion, or if it was in some way accidental, and if the standard says anything about allowed implicit conversions.

On a related note, I'm wondering if using `std::filesystem::path` might encourage code with cross platform issues, such as what happened with the unit tests. Mind you, we have CI builds for all platforms and all relevant projects that would catch such things.
