### ISSUE TITLE
Add Vector3<T> type

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#974]
See https://github.com/OutpostUniverse/OPHD/issues/1039

**Comment by DanRStevens** [comment]
Two thoughts come to mind when I read this issue:
1. The NAS2D library doesn't actually use any 3D points, so it's not clear if this should be supported here, or left to downstream projects, such as OPHD.
2. The proposal to add a `Vector3` basically implies code duplication. It might make more sense to parameterize the existing `Vector` class to allow a dimension to be specified, rather than duplicating all the code. Though if the fields were made to be generic for a N-dimensional vector, we would likely lose the familiar names `x` and `y`.

**Comment by cugone** [comment]
Having more dimensions than 4 is not something the game industry uses. Generalizing the code in such a way to allow N-dimensions would be a waste of brain power and time. Also, a lot of the duplicated code can be moved to a MathUtils namespace with `Vector2/3/4` overloads (`dotProduct`, `crossProduct`, `reflect`, `normalize`, etc.)

**Comment by DanRStevens** [comment]
I'm really not in favour of adding names such as `Vector2/3/4`, where the dimension is baked into the name.

Some consideration also needs to be given to maintenance. Sometimes method implementations change. If you've duplicated code for multiple dimensions, you multiply the maintenance effort to keep that code up to date.

**Comment by cugone** [comment]
Once they are written, the vector classes never change, barring actual language changes, (a rare thing). due to them being ingrained into *everything*. Changing my vector class header causes an entire rebuild of the engine. I imagine trying to unnecessarily templatize it will make that worse because there is only a header file.

**Comment by DanRStevens** [comment]
You say that, and then immediate make a bug fix to one of the classes, without also updating the other class. :expressionless:

**Comment by ldicker83** [comment]
So I'm not sure a Vector3 would make sense but a Point2D and a Point3D would make sense.

In a 2D game I'm not sure 3-axis vectors would really be of any use knowing how they're applied, but there are times even in a 2D game where a 3D point does make sense. E.g., in OPHD, the coordinates of a map tile are technically 3D -- X, Y and then a depth. I just had to address this in one of my recent releases and was thinking how useful it would be to have a 3d point.

**Comment by ldicker83** [comment]
Gonna close this for now as I don't really see the need for a 3-value vector, it's not the direction I want to go with NAS2D.
